version: "3.9"

services:
  react-app:
    container_name: react-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80" 
    volumes:
      - .:/app 
      - /app/node_modules 
